workflows:
  android-production:
    name: Android Production Build
    instance_type: linux_x2  # Cheaper than Mac for Android
    max_build_duration: 60
    environment:
      groups:
        - Production
      vars:
        EAS_PROFILE: production
        EAS_NO_VCS: "1"
      node: 18
      # Android signing configuration
      android_signing:
        - PiggusProd
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: yarn install

      - name: Install EAS CLI
        script: yarn global add eas-cli

      - name: Prebuild Expo project
        script: yarn expo prebuild --platform android

      - name: Build Android locally
        script: eas build --local --platform android --profile $EAS_PROFILE

      - name: Upload Sentry sourcemaps (Android)
        script: |
          npx sentry-cli releases new "$CM_BUILD_ID-android"
          npx sentry-cli releases files "$CM_BUILD_ID-android" upload-sourcemaps ./ --rewrite --url-prefix "~/"
          npx sentry-cli releases finalize "$CM_BUILD_ID-android"

    artifacts:
      - build/**/*.apk
      - build/**/*.aab

    publishing:
      google_play:
        credentials: $GOOGLE_PLAY_SERVICE_ACCOUNT_CREDENTIALS
        track: internal  # Options: internal, alpha, beta, production
        submit_as_draft: false  # Creates draft for manual review before publishing
        release_promotion:
          track: production
          promote_as_draft: true

  ios-production:
    name: iOS Production Build
    instance_type: mac_mini_m1  # Required for iOS builds
    max_build_duration: 60
    integrations:
      app_store_connect: Codemagic Piggus
    environment:
      groups:
        - Production
      vars:
        EAS_PROFILE: production
        EAS_NO_VCS: "1"
      node: 18
      xcode: latest
      # iOS signing configuration
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.rebelpug.piggus
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
    scripts:
      - name: Install dependencies
        script: yarn install

      - name: Install EAS CLI
        script: yarn global add eas-cli

      - name: Prebuild Expo project
        script: yarn expo prebuild --platform ios

      - name: Build iOS locally
        script: eas build --local --platform ios --profile $EAS_PROFILE

      - name: Upload Sentry sourcemaps (iOS)
        script: |
          npx sentry-cli releases new "$CM_BUILD_ID-ios"
          npx sentry-cli releases files "$CM_BUILD_ID-ios" upload-sourcemaps ./ --rewrite --url-prefix "~/"
          npx sentry-cli releases finalize "$CM_BUILD_ID-ios"

    artifacts:
      - ios/build/**/*.ipa

    publishing:
      app_store_connect:
        auth: integration  # You need to set up App Store Connect integration in Codemagic UI
        submit_to_testflight: true  # Automatic beta testing
        submit_to_app_store: false  # Manual App Store submission for production
